lexik_translation_grid:
    pattern:  /translation/grid
    defaults: { _controller: "LexikTranslationBundle:Edition:grid" }

lexik_translation_list:
    pattern:  /translation/list
    defaults: { _controller: "LexikTranslationBundle:Edition:list" }

lexik_translation_update:
    pattern:      /translation/update
    defaults:     { _controller: "LexikTranslationBundle:Edition:update" }
    requirements: { _method: POST }

lexik_translation_new:
    pattern:  /translation/new
    defaults: { _controller: "LexikTranslationBundle:Edition:new" }

lexik_translation_invalidate_cache:
    pattern:  /translation/invalidate-cache
    defaults: { _controller: "LexikTranslationBundle:Edition:invalidateCache" }
